name: Example for @actions/cache

on:
  workflow_dispatch:
    inputs:
      cacheKey:
        description: 'Cache key'
        required: true

jobs:
  cache:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run a script that uses @actions/cache
      run: node ./scripts/cache-example.js
